services:
  - type: web
    name: eco-vehicle-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd web && gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: AUTODESK_CLIENT_ID
        value: Gb5FqoCZj4jMGFGqQUKe6r8DEz5cdq96stVVeX5hnblLmfs9
      - key: AUTODESK_CLIENT_SECRET
        value: RTdFbxewamXc1JJYSaieft6gXAP5URrfuAEZO4LMuSIHY4oq3ltY5qd5p4PEm3Hd
      - key: FORGE_CALLBACK_URL
        value: https://eco-vehicle-app.onrender.com/api/forge/callback
      - key: MODEL_DERIVATIVE_API_URL
        value: https://developer.api.autodesk.com/modelderivative/v2/
      - key: FORGE_BUCKET_KEY
        value: ecovehicleapp20250227
      - key: FLASK_SECRET_KEY
        value: eco_vehicle_secret_key_2025
      - key: REDIS_URL
        fromService:
          type: redis
          name: eco-vehicle-redis
          property: connectionString

  - type: redis
    name: eco-vehicle-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free
