network:
  version: 2
  renderer: networkd
  ethernets:
    # Primary ethernet interface
    eno1:
      addresses: [192.168.2.4/24]
      routes:
        - to: default
          via: 192.168.2.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
      dhcp4: no
      optional: true
